# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0002_auto_20180619_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
