# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-11 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
