# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-11 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20180611_0742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
