# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-11 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20180611_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='occupation',
            new_name='education',
        ),
    ]
