# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_auto_20180613_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
