# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_auto_20180613_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
