# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_program_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
