# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModPy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModPy',
            new_name='Module',
        ),
    ]
