# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModPy', '0002_auto_20180614_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='Some description'),
        ),
    ]
