# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModPy', '0004_auto_20180620_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Indent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='Optional',
            field=models.CharField(default='Optional', max_length=150),
        ),
        migrations.AlterField(
            model_name='module',
            name='InputType',
            field=models.CharField(default='Some type', max_length=150),
        ),
    ]
