# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModPy', '0005_auto_20180620_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='IsInFunction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='dev_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='var_decl',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='module',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
